---
- name: Copy K3s token from master node
  copy:
    src: "/tmp/k3s_token"
    dest: "/tmp/k3s_token"
    mode: '0600'

- name: Install K3s agent
  shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['master'].ansible_host }}:6443 K3S_TOKEN={{ lookup('file', '/tmp/k3s_token') }} sh -s - --node-ip={{ ansible_host }}"  #FIXME: --server {{ hostvars['master'].ansible_host }} ?
  become: yes

- name: Delete the Tokenfile
  file:
    path: "/tmp/k3s_token"
    state: absent
