---
- name: Copy values.yaml Grafana file
  copy:
    src: values.yaml
    dest: /tmp/grafana-values.yaml

- name: Deploy Grafana using Helm
  become: yes
  kubernetes.core.helm:
    name: grafana
    chart_repo_url: https://grafana.github.io/helm-charts
    chart_ref: grafana
    release_namespace: monitoring
    create_namespace: true
    values_files:
      - /tmp/grafana-values.yaml

- name: Delete unused values.yaml file
  file:
    path: /tmp/grafana-values.yaml
    state: absent