adminUser: admin
adminPassword: password
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local:80
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'dp1'
        orgId: 1
        folder: 'graf-dashboards'
        type: 'file'
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/dp1

dashboardsConfigMaps:
  dp1: "grafana-dashboards"

#dashboards:
#  default:
#    kubernetes-dashboard:
#      file: /var/lib/grafana/dashboards/6417_rev1.json

#extraVolumes:
#  - name: grafana-dashboards
#    configMap:
#      name: grafana-dashboards

#extraVolumeMounts:
#  - name: grafana-dashboards
#    mountPath: /var/lib/grafana/dashboards
#    readOnly: true


#from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml