---
- name: Copy Prometheus values.yaml file
  copy:
    src: values.yaml
    dest: '/tmp/prometheus-values.yaml'
    mode: '0600'

- name: Install Prometheus with Helm
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus
    chart_repo_url: https://prometheus-community.github.io/helm-charts
    release_namespace: monitoring
    create_namespace: true
    values:  # TODO: merge this in values.yaml
      alertmanager:
        enabled: true
      server:
        service:
          type: ClusterIP
    state: present
    values_files:
      - /tmp/prometheus-values.yaml

- name: Delete Prometheus used values.yaml file
  file:
    path: '/tmp/prometheus-values.yaml'
    state: absent